/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package document;

import admin.admindashboard;
import barangaydocumentrequestsystem.Loginform;
import config.Session;
import config.dbConnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Macky Server
 */
public class documentsdata extends javax.swing.JFrame {
    String selectedId = "";
    /**
     * Creates new form documentsdata
     */
    public documentsdata() {
        initComponents();
        displayData();
    }
    public void displayData() {
    try {
        dbConnector dbc = new dbConnector();
        // Correct query for your tbl_documents table
        ResultSet rs = dbc.getData("SELECT d_id, d_type, d_price FROM tbl_documents");
        docstable.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch (SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        docstable = new javax.swing.JTable();
        docsnum = new javax.swing.JPanel();
        numofdocs = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        refdocs = new javax.swing.JButton();
        adddocs = new javax.swing.JButton();
        editdocs = new javax.swing.JButton();
        deldocs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(637, 349));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Documents Data");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 230, 29));

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        docstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(docstable);

        docsnum.setBackground(new java.awt.Color(204, 204, 204));
        docsnum.setLayout(null);

        numofdocs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numofdocs.setText("documents");
        docsnum.add(numofdocs);
        numofdocs.setBounds(2, 70, 100, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LOGOOOOOOOOO-removebg-preview.png"))); // NOI18N
        docsnum.add(jLabel4);
        jLabel4.setBounds(20, 10, 70, 60);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(docsnum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docsnum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 540, 300));

        refdocs.setText("REFRESH");
        refdocs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refdocsMouseClicked(evt);
            }
        });
        jPanel1.add(refdocs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 30));

        adddocs.setText("ADD");
        adddocs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adddocsMouseClicked(evt);
            }
        });
        jPanel1.add(adddocs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 30));

        editdocs.setText("EDIT");
        editdocs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editdocsMouseClicked(evt);
            }
        });
        jPanel1.add(editdocs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 30));

        deldocs.setText("DELETE");
        deldocs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deldocsMouseClicked(evt);
            }
        });
        jPanel1.add(deldocs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        admindashboard ds = new admindashboard();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void docstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docstableMouseClicked
        int row = docstable.getSelectedRow();
        selectedId = docstable.getValueAt(row, 0).toString(); // Get d_id
    }//GEN-LAST:event_docstableMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     Session ses = Session.getInstance();

    if (ses.getId() == 0) {
        JOptionPane.showMessageDialog(null, "You must log in first.");
        Loginform lf = new Loginform();
        lf.setVisible(true);
        this.dispose();
    } else {
        dbConnector dbc = new dbConnector();
        try {
            ResultSet rs = dbc.getData("SELECT COUNT(*) AS total FROM tbl_documents");
            if (rs.next()) {
                int count = rs.getInt("total");
                numofdocs.setText("Documents: "+ count);
            }
            rs.close();
        } catch (Exception ex) {
            System.out.println("Error retrieving document count: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_formWindowActivated

    private void adddocsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adddocsMouseClicked
        this.dispose();
        createnewdocs cds = new createnewdocs();
        cds.setVisible(true);
    }//GEN-LAST:event_adddocsMouseClicked

    private void editdocsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editdocsMouseClicked
        if (selectedId.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a document to edit.");
        return;
    }

    dbConnector dbc = new dbConnector();
    try {
        String query = "SELECT * FROM tbl_documents WHERE d_id = '" + selectedId + "'";
        ResultSet rs = dbc.getData(query);

        if (rs.next()) {
            createnewdocs editForm = new createnewdocs();

            // Set fields in the edit form
            editForm.did.setText(rs.getString("d_id"));
            editForm.dtype.setText(rs.getString("d_type"));
            editForm.dprice.setText(rs.getString("d_price"));

            // Disable ID editing so that the ID can't be changed
            editForm.did.setEnabled(false);

            // Show the edit form
            editForm.setVisible(true);
            this.dispose(); // Close the current form after opening the edit form
        }

        rs.close();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error loading document data: " + ex.getMessage());
    }
    }//GEN-LAST:event_editdocsMouseClicked

    private void deldocsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deldocsMouseClicked
        if (selectedId.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please select a document to delete.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this document?", "Confirm Delete", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        dbConnector dbc = new dbConnector();
        String deleteQuery = "DELETE FROM tbl_documents WHERE d_id = '" + selectedId + "'";
        boolean result = dbc.updateData(deleteQuery);

        if (result) {
            JOptionPane.showMessageDialog(null, "Document deleted successfully.");
            displayData();
            selectedId = "";
        } else {
            JOptionPane.showMessageDialog(null, "Failed to delete document.");
        }
    }
    }//GEN-LAST:event_deldocsMouseClicked

    private void refdocsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refdocsMouseClicked
        displayData(); // Reload table data
        selectedId = ""; // Clear selection
    }//GEN-LAST:event_refdocsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(documentsdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(documentsdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(documentsdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(documentsdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new documentsdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddocs;
    private javax.swing.JButton deldocs;
    private javax.swing.JPanel docsnum;
    private javax.swing.JTable docstable;
    private javax.swing.JButton editdocs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numofdocs;
    private javax.swing.JButton refdocs;
    // End of variables declaration//GEN-END:variables
}
